### ISSUE TITLE
No such container resinstack/emissary

### ISSUE THREAD

**Issue by spuder** [the-maldridge/resinstack#2]
I find when building the images, that it is unable to find an image named `resinstack/emissary`. 

That image does not appear in the docker hub. I suspect it is either build locally, or it is in a private docker hub that I don't have access to. 

```
Pull image: docker.io/resinstack/emissary:v0.1.0
FATA[0010] Failed to create OCI spec for resinstack/emissary:v0.1.0: Error response from daemon: pull access denied for resinstack/emissary, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [img/consul.qcow2] Error 1
```

**Comment by the-maldridge** [comment]
I have pushed the container.  You should now be able to pull it.
